const greenhouse = [
  // GEN AI & ML ENGINEERING (Best for AI Engineers)
  { name: "OpenAI", slug: "openai" },
  { name: "Anthropic", slug: "anthropic" },
  { name: "Cohere", slug: "cohere" },
  { name: "Mistral AI", slug: "mistralai" },
  { name: "Hugging Face", slug: "huggingface" },
  { name: "Replicate", slug: "replicate" },
  { name: "Runway", slug: "runwayml" },
  { name: "Midjourney", slug: "midjourney" },
  { name: "Stability AI", slug: "stabilityai" },
  { name: "Cerebras", slug: "cerebras" },
  { name: "Scale AI", slug: "scaleai" },
  { name: "Weights & Biases", slug: "wandb" },
  { name: "Comet ML", slug: "comet" },
  { name: "Neptune AI", slug: "neptune" },
  { name: "Determined AI", slug: "determined" },
  { name: "Modal", slug: "modal" },
  { name: "Replit", slug: "replit" },
  { name: "Coder", slug: "coder" },
  { name: "Gitpod", slug: "gitpod" },
  
  // FRONTEND HEAVY (React/Vue/Next.js)
  { name: "Vercel", slug: "vercel" },
  { name: "Netlify", slug: "netlify" },
  { name: "Cloudflare", slug: "cloudflare" },
  { name: "Figma", slug: "figma" },
  { name: "Linear", slug: "linear" },
  { name: "Notion", slug: "notion" },
  { name: "Cal.com", slug: "cal" },
  { name: "Loom", slug: "loom" },
  { name: "Webflow", slug: "webflow" },
  { name: "Bubble", slug: "bubble" },
  { name: "Builder.io", slug: "builderio" },
  { name: "Plasmic", slug: "plasmic" },
  { name: "Retool", slug: "retool" },
  { name: "Appsmith", slug: "appsmith" },
  { name: "ToolJet", slug: "tooljet" },
  { name: "Storybook", slug: "storybook" },
  { name: "Chromatic", slug: "chromatic" },
  { name: "Vite", slug: "vite" },
  { name: "NuxtJS", slug: "nuxtjs" },
  { name: "NextJS", slug: "nextjs" },
  { name: "Gatsby", slug: "gatsby" },
  { name: "Sanity", slug: "sanity" },
  { name: "Contentful", slug: "contentful" },
  { name: "Strapi", slug: "strapi" },
  { name: "Ghost", slug: "ghost" },
  { name: "WordPress", slug: "wordpress" },
  { name: "Shopify", slug: "shopify" },
  
  // BACKEND/INFRA/DEVOPS
  { name: "Vercel", slug: "vercel" },
  { name: "Netlify", slug: "netlify" },
  { name: "Cloudflare", slug: "cloudflare" },
  { name: "Fastly", slug: "fastly" },
  { name: "Akamai", slug: "akamai" },
  { name: "Datadog", slug: "datadog" },
  { name: "Sentry", slug: "sentry" },
  { name: "New Relic", slug: "newrelic" },
  { name: "Splunk", slug: "splunk" },
  { name: "Elastic", slug: "elastic" },
  { name: "Grafana Labs", slug: "grafana" },
  { name: "InfluxData", slug: "influxdata" },
  { name: "Timescale", slug: "timescale" },
  { name: "CockroachDB", slug: "cockroachlabs" },
  { name: "PlanetScale", slug: "planetscale" },
  { name: "Neon", slug: "neondatabase" },
  { name: "Supabase", slug: "supabasehq" },
  { name: "Convex", slug: "convex" },
  { name: "Firebase", slug: "firebase" },
  { name: "AppWrite", slug: "appwrite" },
  { name: "Nhost", slug: "nhost" },
  { name: "Hasura", slug: "hasura" },
  { name: "Postman", slug: "postman" },
  { name: "Kong", slug: "kong" },
  { name: "Tyk", slug: "tyk" },
  { name: "Apollo", slug: "apollographql" },
  { name: "Prisma", slug: "prisma" },
  { name: "Drizzle", slug: "drizzle" },
  { name: "TypeORM", slug: "typeorm" },
  { name: "Sequelize", slug: "sequelize" },
  { name: "Mongoose", slug: "mongoose" },
  
  // FULL STACK (Good for both FE/BE)
  { name: "Vercel", slug: "vercel" },
  { name: "Netlify", slug: "netlify" },
  { name: "Cloudflare", slug: "cloudflare" },
  { name: "Render", slug: "render" },
  { name: "Railway", slug: "railway" },
  { name: "Fly.io", slug: "flyio" },
  { name: "Heroku", slug: "heroku" },
  { name: "DigitalOcean", slug: "digitalocean" },
  { name: "Linode", slug: "linode" },
  { name: "Vultr", slug: "vultr" },
  { name: "AWS", slug: "amazon" },
  { name: "Google Cloud", slug: "google" },
  { name: "Microsoft Azure", slug: "microsoft" },
  { name: "IBM Cloud", slug: "ibm" },
  { name: "Oracle Cloud", slug: "oracle" },
  { name: "Alibaba Cloud", slug: "alibaba" },
  { name: "Tencent Cloud", slug: "tencent" },
  { name: "Baidu Cloud", slug: "baidu" },
];

const lever = [
  // GEN AI ENGINEERING
  { name: "OpenAI", slug: "openai" },
  { name: "Anthropic", slug: "anthropic" },
  { name: "Cohere", slug: "cohere" },
  { name: "Mistral AI", slug: "mistralai" },
  { name: "Hugging Face", slug: "huggingface" },
  { name: "Replicate", slug: "replicate" },
  { name: "Runway", slug: "runwayml" },
  { name: "Midjourney", slug: "midjourney" },
  { name: "Stability AI", slug: "stabilityai" },
  { name: "Cerebras", slug: "cerebras" },
  { name: "Scale AI", slug: "scaleai" },
  { name: "Weights & Biases", slug: "wandb" },
  { name: "Comet ML", slug: "comet" },
  { name: "Neptune AI", slug: "neptune" },
  { name: "Determined AI", slug: "determined" },
  { name: "Modal", slug: "modal" },
  { name: "Replit", slug: "replit" },
  { name: "Coder", slug: "coder" },
  { name: "Gitpod", slug: "gitpod" },
  
  // FRONTEND FOCUSED
  { name: "Figma", slug: "figma" },
  { name: "Linear", slug: "linear" },
  { name: "Notion", slug: "notion" },
  { name: "Cal.com", slug: "cal" },
  { name: "Loom", slug: "loom" },
  { name: "Webflow", slug: "webflow" },
  { name: "Bubble", slug: "bubble" },
  { name: "Builder.io", slug: "builderio" },
  { name: "Plasmic", slug: "plasmic" },
  { name: "Retool", slug: "retool" },
  { name: "Appsmith", slug: "appsmith" },
  { name: "ToolJet", slug: "tooljet" },
  { name: "Storybook", slug: "storybook" },
  { name: "Chromatic", slug: "chromatic" },
  { name: "Vite", slug: "vite" },
  { name: "NuxtJS", slug: "nuxtjs" },
  { name: "NextJS", slug: "nextjs" },
  { name: "Gatsby", slug: "gatsby" },
  { name: "Sanity", slug: "sanity" },
  { name: "Contentful", slug: "contentful" },
  { name: "Strapi", slug: "strapi" },
  { name: "Ghost", slug: "ghost" },
  { name: "WordPress", slug: "wordpress" },
  { name: "Shopify", slug: "shopify" },
  
  // BACKEND/INFRA
  { name: "Datadog", slug: "datadog" },
  { name: "Sentry", slug: "sentry" },
  { name: "New Relic", slug: "newrelic" },
  { name: "Splunk", slug: "splunk" },
  { name: "Elastic", slug: "elastic" },
  { name: "Grafana Labs", slug: "grafana" },
  { name: "InfluxData", slug: "influxdata" },
  { name: "Timescale", slug: "timescale" },
  { name: "CockroachDB", slug: "cockroachlabs" },
  { name: "PlanetScale", slug: "planetscale" },
  { name: "Neon", slug: "neondatabase" },
  { name: "Supabase", slug: "supabasehq" },
  { name: "Convex", slug: "convex" },
  { name: "Firebase", slug: "firebase" },
  { name: "AppWrite", slug: "appwrite" },
  { name: "Nhost", slug: "nhost" },
  { name: "Hasura", slug: "hasura" },
  { name: "Postman", slug: "postman" },
  { name: "Kong", slug: "kong" },
  { name: "Tyk", slug: "tyk" },
  { name: "Apollo", slug: "apollographql" },
  { name: "Prisma", slug: "prisma" },
  { name: "Drizzle", slug: "drizzle" },
  { name: "TypeORM", slug: "typeorm" },
  { name: "Sequelize", slug: "sequelize" },
  { name: "Mongoose", slug: "mongoose" },
];

 
const workable = [
  // GEN AI
  { name: "Jasper AI", slug: "jasper" },
  { name: "Copy.ai", slug: "copyai" },
  { name: "Writer", slug: "writer" },
  { name: "Grammarly", slug: "grammarly" },
  { name: "Descript", slug: "descript" },
  { name: "Synthesia", slug: "synthesia" },
  { name: "D-ID", slug: "did" },
  { name: "Murf AI", slug: "murfai" },
  { name: "Play.ht", slug: "playht" },
  { name: "Resemble AI", slug: "resembleai" },
  
  // FRONTEND
  { name: "Tailwind CSS", slug: "tailwindcss" },
  { name: "Vue.js", slug: "vuejs" },
  { name: "Svelte", slug: "svelte" },
  { name: "Alpine.js", slug: "alpinejs" },
  { name: "Stimulus", slug: "stimulus" },
  { name: "Hotwire", slug: "hotwire" },
  { name: "Turbo", slug: "turbo" },
  { name: "StimulusReflex", slug: "stimulusreflex" },
  { name: "CableReady", slug: "cableready" },
  
  // BACKEND
  { name: "NestJS", slug: "nestjs" },
  { name: "FastAPI", slug: "fastapi" },
  { name: "Express.js", slug: "expressjs" },
  { name: "Koa", slug: "koa" },
  { name: "Hapi", slug: "hapi" },
  { name: "Sails.js", slug: "sailsjs" },
  { name: "Meteor", slug: "meteor" },
  { name: "Feathers.js", slug: "feathersjs" },
  { name: "LoopBack", slug: "loopback" },
  { name: "AdonisJS", slug: "adonisjs" },
  
  // DEVOPS
  { name: "Docker", slug: "docker" },
  { name: "Kubernetes", slug: "kubernetes" },
  { name: "Helm", slug: "helm" },
  { name: "Terraform", slug: "terraform" },
  { name: "Pulumi", slug: "pulumi" },
  { name: "Ansible", slug: "ansible" },
  { name: "Chef", slug: "chef" },
  { name: "Puppet", slug: "puppet" },
  { name: "SaltStack", slug: "saltstack" },
  { name: "Vagrant", slug: "vagrant" },
];

// SPECIFIC FOR STUDENT SDE ROLES (These hire interns/juniors)
const studentSDEStartups = {
  greenhouse: [
    // Good for internships
    { name: "Vercel", slug: "vercel" },
    { name: "Netlify", slug: "netlify" },
    { name: "Figma", slug: "figma" },
    { name: "Linear", slug: "linear" },
    { name: "Notion", slug: "notion" },
    { name: "Cal.com", slug: "cal" },
    { name: "Loom", slug: "loom" },
    { name: "Render", slug: "render" },
    { name: "Railway", slug: "railway" },
    { name: "Supabase", slug: "supabasehq" },
    { name: "PlanetScale", slug: "planetscale" },
    { name: "Neon", slug: "neondatabase" },
    { name: "Convex", slug: "convex" },
    { name: "Clerk", slug: "clerk" },
    { name: "Sentry", slug: "sentry" },
    { name: "Postman", slug: "postman" },
  ],
  
  lever: [
    // Good for junior roles
    { name: "Figma", slug: "figma" },
    { name: "Linear", slug: "linear" },
    { name: "Notion", slug: "notion" },
    { name: "Cal.com", slug: "cal" },
    { name: "Loom", slug: "loom" },
    { name: "Render", slug: "render" },
    { name: "Railway", slug: "railway" },
    { name: "Supabase", slug: "supabasehq" },
    { name: "PlanetScale", slug: "planetscale" },
    { name: "Neon", slug: "neondatabase" },
    { name: "Convex", slug: "convex" },
    { name: "Clerk", slug: "clerk" },
    { name: "Sentry", slug: "sentry" },
    { name: "Postman", slug: "postman" },
  ],
  
  // REMOTE-FIRST (Great for location-independent)
  remoteFirst: [
    { name: "GitLab", slug: "gitlab" },
    { name: "Automattic", slug: "automattic" },
    { name: "Zapier", slug: "zapier" },
    { name: "Buffer", slug: "buffer" },
    { name: "Doist", slug: "doist" },
    { name: "Toggl", slug: "toggl" },
    { name: "Hotjar", slug: "hotjar" },
    { name: "Help Scout", slug: "helpscout" },
    { name: "Close", slug: "close" },
    { name: "ConvertKit", slug: "convertkit" },
  ]
};

export {
  greenhouse,
  lever,
  workable,
  studentSDEStartups
};